# Generated by Django 4.2.16 on 2024-09-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estudei", "0005_alter_entry_back_alter_entry_front"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="back",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="front",
        ),
    ]
