# Generated by Django 4.2.16 on 2024-09-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudei", "0003_topic_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={},
        ),
        migrations.RemoveField(
            model_name="entry",
            name="text",
        ),
        migrations.AddField(
            model_name="entry",
            name="back",
            field=models.TextField(
                blank=True,
                help_text="Texto que aparece no verso do flashcard.",
                verbose_name="Verso do Flashcard",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="front",
            field=models.TextField(
                blank=True,
                help_text="Texto que aparece na frente do flashcard.",
                verbose_name="Frente do Flashcard",
            ),
        ),
    ]
