# Generated by Django 4.2.16 on 2024-09-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estudei", "0004_alter_entry_options_remove_entry_text_entry_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="back",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="front",
            field=models.TextField(),
        ),
    ]
